# Generated by Django 5.2 on 2025-04-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_user_options_user_user_user_email_5f6a77_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresettoken",
            name="token",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
