# Generated by Django 4.1 on 2025-04-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transport", "0004_journey"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journey",
            name="arrival_time",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="journey",
            name="departure_time",
            field=models.DateTimeField(),
        ),
    ]
