# Generated by Django 5.2 on 2025-04-25 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transport", "0006_order_ticket"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="route",
            unique_together={("source", "destination")},
        ),
    ]
